name: do_algorithm!

on:
  schedule:
    - cron: "0 15 * * 0-4"
    #- cron: "*/5 * * * *"

jobs:
  create_issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
      - name: Get today date
        id: date
        run: |
          echo "DATE=$(TZ=Asia/Seoul date "+%Y/%m/%d") >> $GITHUB_ENV"
      - name: Create issue for Algorithm problem solving
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "jis-kim"
          title: "[주제] 문제"
          body: |
            # ${{ env.DATE }}
            ## 주제
              - 완전탐색
            ## 문제 링크
              - https://school.programmers.co.kr/learn/courses/30/parts/12230
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
